version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: agent932-intel-gpu-monitor_web_1
      APP_PORT: 8847

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8847:8847"
    environment:
      - NODE_ENV=production
      - PORT=8847
      - PLEX_URL=${PLEX_URL:-}
      - PLEX_TOKEN=${PLEX_TOKEN:-}
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./data:/data
      - /sys/kernel/debug:/sys/kernel/debug:ro

  widget-server:
    build:
      context: .
      dockerfile: Dockerfile.widget
    restart: on-failure
    ports:
      - "8880:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - MAIN_SERVER_URL=http://web:8847
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug:ro
